Num1=int(input("Enter Unique Num1 : "))
Num2=int(input("Enter Unique Num2 : "))
Num3=int(input("Enter Unique Num3 : "))
Num4=int(input("Enter Unique Num4 : "))
Num5=int(input("Enter Unique Num5 : "))
Num6=int(input("Enter Unique Num6 : "))
Num7=int(input("Enter Unique Num7 : "))
Num8=int(input("Enter Unique Num8 : "))
a={Num1,Num2,Num3,Num4,Num5,Num6,Num7,Num8}
print("Unique Nums are :",a)